name: Generate snake animation

on:
  schedule: # Execute a cada 12 horas
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clonar o reposit칩rio
        uses: actions/checkout@v2

      - name: Gerar snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark
          # Par칙metros adicionais para ajustar a 치rea de comida (se suportado)
          color_snake: "#FF00FF" # Define a cor da cobra (opcional)
          color_dots: "#00FF00"  # Define a cor dos pontos (comida) (opcional)
          # Defina pixels_per_hour para ajustar a densidade do grid
          pixels_per_hour: 20    # Tente diferentes valores para ajustar a 치rea de comida

      - name: Push snake.svg para o branch de output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
